from .bfs import breadth_first_search_version_1, breadth_first_search_version_2
from .dfs import depth_first_search_version_1, depth_first_search_version_2
from .ids import iterative_deepening_search_version_1, iterative_deepening_search_version_2
from .ucs import uniform_cost_search
from .greedy_search import greedy_search
from .a_star import a_star_search
from .ida_star import iterative_deepening_a_star
from .hill_climbing import simple_hill_climbing, steepest_ascent_hill_climbing, stochastic_hill_climbing, randomm_restart_hill_climbing
from .local_beam_search import local_beam_search
from .simulated_annealing import simulated_annealing